# -*- coding: utf-8 -*-
"""Anime skin database.

Field order:
slug, title, page (Wikipedia page title for the character image),
cat, desc, agent, welcome, goodbye, sym, verbs, p, s, a, bg, tx, skills, logo
"""

ANIME = [
    # ---------------- Action ----------------
    ("naruto", "Naruto", "Naruto Uzumaki", "Action",
     "The ninja who never gives up — shadow clones, Rasengan, ramen.",
     "Hokage Agent", "Believe it! Type your message or /help, ninja!",
     "That's my ninja way! Later!",
     "❂", ["training with shadow clones", "becoming Hokage", "eating ramen", "learning jutsu", "never giving up"],
     "#F97316", "#2563EB", "#FDE047", "#0F0904", "#F7EFE5",
     ["Shadow Clone", "Rasengan", "Ninja Way"], "NARUTO"),

    ("one-piece", "One Piece", "Monkey D. Luffy", "Action",
     "The future Pirate King sails the Grand Line with his straw hat crew.",
     "Pirate Agent", "Gear Fifth! Type your message or /help, nakama!",
     "The adventure continues! Later!",
     "☠", ["sailing the Grand Line", "becoming Pirate King", "stretching for victory", "finding the One Piece", "battling the Marines"],
     "#DC2626", "#FACC15", "#38BDF8", "#0F0505", "#F7E9E9",
     ["Gum-Gum Fruit", "Gear Fifth", "Conqueror's Haki"], "ONE PIECE"),

    ("dragon-ball-z", "Dragon Ball Z", "Goku", "Action",
     "The Saiyan who keeps breaking his own limits.",
     "Z-Fighter Agent", "Power level over 9000! Type your message or /help!",
     "Earth is safe. See you in the next saga!",
     "☄", ["charging the Kamehameha", "going Super Saiyan", "powering up", "training with Whis", "fighting Frieza"],
     "#F97316", "#3B82F6", "#FDE047", "#0F0904", "#F7EFE5",
     ["Kamehameha", "Super Saiyan", "Instant Transmission"], "DRAGON BALL Z"),

    ("bleach", "Bleach", "Ichigo Kurosaki", "Action",
     "The substitute Soul Reaper with a very big sword.",
     "Soul Reaper Agent", "Bankai! Type your message or /help, Soul Reaper!",
     "The hollows are gone. Later!",
     "✚", ["releasing Bankai", "fighting hollows", "training in the Soul Society", "protecting Karakura", "mastering the Zanpakutō"],
     "#F97316", "#F8FAFC", "#EF4444", "#0F0904", "#F5F1E8",
     ["Bankai", "Getsuga Tenshō", "Hollow Mask"], "BLEACH"),

    ("demon-slayer", "Demon Slayer", "Tanjiro Kamado", "Action",
     "The kind-hearted demon slayer fighting to save his sister.",
     "Slayer Agent", "Total concentration! Type your message or /help, slayer!",
     "The demons are vanquished. Later!",
     "✷", ["breathing techniques", "slaying demons", "training with the Hashira", "protecting Nezuko", "hunting Muzan"],
     "#15803D", "#94A3B8", "#EF4444", "#04100A", "#E9F5EE",
     ["Water Breathing", "Sun Breathing", "Nezuko Protection"], "DEMON SLAYER"),

    ("my-hero-academia", "My Hero Academia", "Izuku Midoriya", "Action",
     "The quirkless kid who became the symbol of hope.",
     "Hero Agent", "Plus Ultra! Type your message or /help, hero in training!",
     "Go beyond! Plus Ultra!",
     "✤", ["going Plus Ultra", "training One For All", "studying at UA", "saving people", "becoming a hero"],
     "#22C55E", "#EF4444", "#FDE047", "#05120B", "#E8F6ED",
     ["One For All", "Full Cowling", "Plus Ultra"], "MY HERO ACADEMIA"),

    ("hunter-x-hunter", "Hunter × Hunter", "Gon Freecss", "Action",
     "The boy hunter searching for his father.",
     "Hunter Agent", "Let's go hunting! Type your message or /help!",
     "The hunt continues! See you!",
     "⛏", ["hunting", "mastering Nen", "climbing the tower", "taking the Hunter Exam", "finding Ging"],
     "#22C55E", "#38BDF8", "#FDE047", "#05100A", "#E8F6EC",
     ["Nen Mastery", "Hunter Exam", "Rock Paper Scissors"], "HUNTER X HUNTER"),

    ("fullmetal-alchemist", "Fullmetal Alchemist", "Edward Elric", "Action",
     "The Fullmetal Alchemist bound by equivalent exchange.",
     "Alchemist Agent", "Equivalent exchange. Type your message or /help.",
     "The Philosopher's Stone quest continues.",
     "✜", ["transmuting", "seeking the Philosopher's Stone", "performing alchemy", "searching for answers", "fighting homunculi"],
     "#D97706", "#DC2626", "#FDE047", "#0D0803", "#F4EEE3",
     ["Alchemy", "Equivalent Exchange", "Automail"], "FULLMETAL"),

    ("yu-yu-hakusho", "Yu Yu Hakusho", "Yusuke Urameshi", "Action",
     "The spirit detective who fights for the living world.",
     "Spirit Detective Agent", "Spirit gun charged! Type your message or /help, detective!",
     "Case closed. Later!",
     "✺", ["hunting demons", "fighting in the Dark Tournament", "charging the Spirit Gun", "protecting the living world", "working with the team"],
     "#3B82F6", "#4ADE80", "#FDE047", "#070E18", "#E6EDF7",
     ["Spirit Gun", "Dark Tournament", "Rei Gun"], "YU YU HAKUSHO"),

    ("inuyasha", "Inuyasha", "Inuyasha (character)", "Action",
     "The half-demon with a very loud 'sit' command.",
     "Inuyasha Agent", "Sit, boy! Type your message or /help!",
     "The shards are sealed. Later!",
     "⛩", ["hunting shards", "purifying the jewel", "fighting Naraku", "sitting Inuyasha", "crossing the well"],
     "#A855F7", "#DC2626", "#FDE047", "#0D0714", "#F2ECF8",
     ["Tessaiga", "Shard Hunting", "Wind Scar"], "INUYASHA"),

    ("jojo-bizarre-adventure", "JoJo's Bizarre Adventure", "Jotaro Kujo", "Action",
     "Yare yare daze — the Stand user with a killer pose.",
     "JoJo Agent", "Yare yare daze. Type your message or /help.",
     "To be continued...",
     "✣", ["posing", "unleashing the Stand", "going Za Warudo", "fighting vampires", "the journey continues"],
     "#A855F7", "#FACC15", "#22D3EE", "#0D0714", "#F2ECF8",
     ["Star Platinum", "Ora Ora", "Za Warudo"], "JOJO"),

    ("one-punch-man", "One Punch Man", "Saitama (One-Punch Man)", "Action",
     "The hero who ends every fight with one punch.",
     "S-Class Agent", "OK! Type your message or /help... or one punch.",
     "One punch. Done. Goodbye!",
     "⊗", ["defeating everything in one punch", "training with Saitama", "hero-ing for fun", "battling monsters", "saving the city"],
     "#DC2626", "#FACC15", "#FDE047", "#0F0505", "#F7E9E9",
     ["One Punch", "Serious Punch", "Hero Association"], "ONE PUNCH MAN"),

    # ---------------- Dark & Gritty ----------------
    ("attack-on-titan", "Attack on Titan", "Eren Yeager", "Dark",
     "Humanity's fight for survival against the Titans.",
     "Scout Agent", "Dedicate your hearts! Type your message or /help, soldier!",
     "The walls stand. Fight on!",
     "✕", ["maneuvering with the ODM gear", "fighting titans", "scouting beyond the walls", "training with the corps", "fighting for humanity"],
     "#8B5A2B", "#DC2626", "#E5E7EB", "#0A0705", "#EFE9E2",
     ["ODM Gear", "Titan Shifting", "Survey Corps"], "TITAN"),

    ("jujutsu-kaisen", "Jujutsu Kaisen", "Satoru Gojo", "Dark",
     "The strongest sorcerer, hiding behind a blindfold.",
     "Sorcerer Agent", "Domain Expansion! Type your message or /help, sorcerer!",
     "Curses exorcised. Later!",
     "❂", ["exorcising curses", "expanding the domain", "fighting with cursed energy", "teaching at Jujutsu High", "being the strongest"],
     "#60A5FA", "#F8FAFC", "#22D3EE", "#060D18", "#E7EEF7",
     ["Limitless", "Six Eyes", "Domain Expansion"], "JUJUTSU KAISEN"),

    ("chainsaw-man", "Chainsaw Man", "Denji", "Dark",
     "The devil hunter who is literally part chainsaw.",
     "Devil Hunter Agent", "Rrring! Type your message or /help, devil hunter!",
     "Devils dealt with. Time for a cigarette.",
     "⛓", ["hunting devils", "revving the chainsaw", "making contracts", "fighting the Gun Devil", "eating bread"],
     "#F97316", "#E5E7EB", "#DC2626", "#0F0904", "#F5F0E8",
     ["Chainsaw Form", "Devil Contracts", "Devil Hunting"], "CHAINSAW MAN"),

    ("tokyo-ghoul", "Tokyo Ghoul", "Ken Kaneki", "Dark",
     "The half-ghoul caught between two worlds.",
     "Ghoul Agent", "Welcome to the ward. Type your message or /help... if you dare.",
     "The mask stays on. Later.",
     "☾", ["hunting", "hiding in the ward", "fighting the CCG", "using the kagune", "surviving"],
     "#64748B", "#DC2626", "#F8FAFC", "#0A0C0E", "#ECEEF1",
     ["Kagune", "Mask Crafting", "Ward Survival"], "TOKYO GHOUL"),

    ("death-note", "Death Note", "Light Yagami", "Dark",
     "The student who became the god of a new world.",
     "Kira Agent", "I am justice. Type your message or /help.",
     "The note closes. Until next time.",
     "✒", ["writing names", "outsmarting L", "being the god of the new world", "escaping suspicion", "playing the game"],
     "#DC2626", "#94A3B8", "#E5E7EB", "#0B0505", "#F3E9E9",
     ["Death Note", "Misdirection", "The Game"], "DEATH NOTE"),

    ("vinland-saga", "Vinland Saga", "Thorfinn (Vinland Saga)", "Dark",
     "From revenge to redemption — the warrior who seeks a peaceful land.",
     "Warrior Agent", "I have no enemies. Type your message or /help.",
     "A true warrior needs no sword. Later.",
     "⚔", ["fighting for revenge", "finding Vinland", "training as a warrior", "escaping the past", "seeking peace"],
     "#64748B", "#D97706", "#F8FAFC", "#0A0C0E", "#EBEDF0",
     ["Dual Daggers", "Warrior's Code", "Vinland Dream"], "VINLAND SAGA"),

    ("code-geass", "Code Geass", "Lelouch Lamperouge", "Dark",
     "The masked prince who will tear down an empire.",
     "Zero Agent", "All hail Lelouch! Type your message or /help.",
     "The plan continues. Zero out.",
     "☷", ["giving orders", "outsmarting Britannia", "wielding the Geass", "leading the Black Knights", "pursuing the plan"],
     "#7C3AED", "#F8FAFC", "#FACC15", "#0C0716", "#F2ECFA",
     ["Geass", "Tactical Genius", "Zero Mask"], "CODE GEASS"),

    ("berserk", "Berserk", "Guts (Berserk)", "Dark",
     "The Black Swordsman dragging a titanic blade across a cursed world.",
     "Black Swordsman Agent", "Struggle, endure, contend. Type your message or /help.",
     "The brand burns on. Later.",
     "⚔", ["wielding the Dragonslayer", "fighting apostles", "hunting demons", "surviving the Eclipse", "pushing forward"],
     "#6B7280", "#DC2626", "#E5E7EB", "#0B0C0E", "#ECEEF1",
     ["Dragonslayer", "Berserker Armor", "Cannon Arm"], "BERSERK"),

    # ---------------- Sci-Fi & Mecha ----------------
    ("cowboy-bebop", "Cowboy Bebop", "Spike Spiegel", "Sci-Fi",
     "Bounty hunters in space, jazz in the background.",
     "Bebop Agent", "See you, space cowboy. Type your message or /help.",
     "Whatever happens, happens. Later!",
     "♪", ["hunting bounties", "jamming with the Bebop crew", "flying the Swordfish", "tracking targets", "eating bell peppers and beef"],
     "#3B82F6", "#DC2626", "#FDE047", "#070D16", "#E5ECF7",
     ["Jeet Kune Do", "Bounty Hunting", "Swordfish II"], "COWBOY BEBOP"),

    ("sword-art-online", "Sword Art Online", "Kirito", "Sci-Fi",
     "The black swordsman trapped in a deadly VRMMO.",
     "SAO Agent", "Link start! Type your message or /help, player!",
     "Logging out. See you in the next world!",
     "⚔", ["clearing the floor", "trapped in Aincrad", "dueling with swords", "leveling up", "surviving the game"],
     "#22D3EE", "#F8FAFC", "#FDE047", "#041218", "#E6F4F8",
     ["Dual Blades", "Solo Clearing", "Starburst Stream"], "SWORD ART"),

    ("steins-gate", "Steins;Gate", "Rintarō Okabe", "Sci-Fi",
     "The self-proclaimed mad scientist and his time machine.",
     "Mad Scientist Agent", "El Psy Kongroo. Type your message or /help!",
     "The world line shifts. Later!",
     "☉", ["inventing time machines", "sending D-Mails", "avoiding SERN", "saving Kurisu", "crossing world lines"],
     "#94A3B8", "#FACC15", "#38BDF8", "#0C0E11", "#EDEFF2",
     ["Phone Microwave", "D-Mail", "Reading Steiner"], "STEINS GATE"),

    ("evangelion", "Neon Genesis Evangelion", "Evangelion (mecha)", "Sci-Fi",
     "The biomechanical titan fighting Angels — and its own pilot.",
     "NERV Agent", "Get in the robot. Type your message or /help.",
     "Synchro rate falling. Until next time.",
     "⚡", ["syncing with the Eva", "fighting Angels", "piloting Unit-01", "facing the AT Field", "getting in the robot"],
     "#7C3AED", "#22D3EE", "#A3E635", "#0B0714", "#F0EAF8",
     ["AT Field", "Unit-01", "Synchronization"], "EVANGELION"),

    ("gundam", "Mobile Suit Gundam", "RX-78-2 Gundam", "Sci-Fi",
     "The white mobile suit that started a hundred wars.",
     "Gundam Pilot", "Gundam, launching! Type your message or /help, pilot!",
     "Mission complete. Returning to base.",
     "✥", ["launching", "fighting Zeon", "piloting the Gundam", "protecting the White Base", "going to space"],
     "#2563EB", "#F8FAFC", "#FACC15", "#060C16", "#E5ECF7",
     ["Beam Saber", "Vulcan Cannons", "Gundam Hammer"], "GUNDAM"),

    # ---------------- Wholesome & Comedy ----------------
    ("sailor-moon", "Sailor Moon", "Usagi Tsukino", "Wholesome",
     "The crybaby guardian fighting evil by moonlight.",
     "Guardian Agent", "Fighting evil by moonlight! Type your message or /help!",
     "Moon prism power! Goodbye!",
     "☾", ["transforming", "fighting evil by moonlight", "protecting love and justice", "activating Moon Prism Power", "fighting the Dark Kingdom"],
     "#F472B6", "#38BDF8", "#FDE047", "#120A14", "#F9EBF3",
     ["Moon Prism Power", "Moon Tiara", "Guardian Team"], "SAILOR MOON"),

    ("spy-x-family", "Spy × Family", "Anya Forger", "Wholesome",
     "The telepathic girl at the heart of the perfect fake family.",
     "Forger Agent", "Waku waku! Type your message or /help!",
     "Mission complete! Peanuts for everyone!",
     "♥", ["reading minds", "keeping the secret", "getting peanuts", "helping the family", "being the best daughter"],
     "#F9A8D4", "#93C5FD", "#FDE047", "#140B12", "#F9ECF4",
     ["Telepathy", "Peanut Radar", "Operation Strix"], "SPY X FAMILY"),

    ("mob-psycho-100", "Mob Psycho 100", "Shigeo Kageyama", "Wholesome",
     "A powerful psychic trying to live an ordinary life.",
     "Mob Agent", "Counting to 100... Type your message or /help!",
     "100%. Goodbye!",
     "∞", ["counting to 100", "unleashing psychic energy", "working at the office", "controlling emotions", "reaching 100 percent"],
     "#2DD4BF", "#A855F7", "#FDE047", "#061514", "#E7F6F5",
     ["Psychic Energy", "100% Mode", "Emotional Control"], "MOB PSYCHO 100"),
]
